### ISSUE TITLE
Getting "key" item reveals the code instead of null

### ISSUE THREAD

**Issue by bver** [coolaj86/node-localStorage#1]
Hello,
it seems that fetching "key" on empty localStorage reveals the code of the db.prototype.key function:

```
global.localStorage = require('localStorage');
console.log(String(localStorage.getItem('key')));
```

prints

```
function (i) {
    i = i || 0;
    return Object.keys(this)[i];
  }
```

(null should be expected).

**Comment by coolaj86** [comment]
I'll look at this tonight.

On Thursday, January 24, 2013, Pavel Suchmann wrote:

> Hello,
> it seems that fetching "key" on empty localStorage reveals the code of the
> db.prototype.key function:
> 
> global.localStorage = require('localStorage');
> console.log(String(localStorage.getItem('key')));
> 
> prints
> 
> function (i) {
>     i = i || 0;
>     return Object.keys(this)[i];
>   }
> 
> (null should be expected).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/coolaj86/node-localStorage/issues/1.

## 

Sent from Gmail Mobile

**Comment by coolaj86** [comment]
Tested Fixed. Please confirm.

:-D

**Comment by bver** [comment]
I can confirm it was fixed. Thank you for this fix (and of course thank you for developing localStorage).
Pavel

ps: However, I have noticed this warning during the installation:

```
npm WARN package.json localStorage@1.0.1 No README.md file found!
```

**Comment by coolaj86** [comment]
fixed.

also: https://github.com/coolaj86/node-dom-storage

AJ ONeal
(317) 426-6525

**Comment by bver** [comment]
It was only a formal warning.
Anyway, thanks.
